name: Update Readme
on:
  schedule:
    - cron: "0 * * * *" # run every hour
  workflow_dispatch:
jobs:
  build:
    name: Update Recent Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "ci(activity): update README with recent activity"
